### ISSUE TITLE
Crashing when running in Xcode15 beta 6

### ISSUE THREAD

**Issue by mvn-khoavo-dn** [react-native-linear-gradient/react-native-linear-gradient#637]
### Description
Crashing when running the app which is built by Xcode15 beta 6

### Crash log
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={390, 0}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.'
libc++abi: terminating due to uncaught exception of type NSException
*** Assertion failure in void _UIGraphicsBeginImageContextWithOptions(CGSize, BOOL, CGFloat, BOOL)(), UIGraphics.m:410`

### Steps to reproduce
Running the app which is built by Xcode15 beta 6 on iOS 17.0 beta device or Simulator iOS 17.0
The application will be crashed immediately after opening.

### Snack, code example, screenshot, or link to a repository
<img width="921" alt="Screenshot 2023-08-16 at 16 32 42" src="https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/33854688/ea99962c-2e7a-4ab5-a82b-cc68e9cce790">
<img width="1395" alt="Screenshot 2023-08-16 at 16 46 05" src="https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/33854688/d35842d2-8c12-48b4-95af-a6deb86c79e0">

### Recommend Solution
I just tried to fix it by replacing **UIGraphicsBeginImageContextWithOptions(self.bounds.size, !hasAlpha, 0.0);** by **[[UIGraphicsImageRenderer alloc] initWithSize: self.bounds.size];**  in **BVLinearGradientLayer.m** file like this screenshot and the app can run normally.
<img width="949" alt="Screenshot 2023-08-17 at 15 35 57" src="https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/33854688/c76408db-2611-431c-a062-9ca0f40f1d77">

Another related issues from Apple's forum: [Running in Xcode15beta crashed
](https://developer.apple.com/forums/thread/731385)

Please check it and update the library as soon as possible. Thank you very much.

**Comment by suwu150** [comment]
I have also encountered the same problem. Has anyone solved it

**Comment by friederbluemle** [comment]
I believe this issue has already been fixed by @Caiopia in #626 - The patch will be part of the upcoming 3.0.0 release (currently in alpha, beta coming soon). It has also been cherry-picked to the 2.8 series: https://github.com/react-native-linear-gradient/react-native-linear-gradient/releases/tag/v2.8.3

**Comment by dehimer** [comment]
Still actual problem. Event after updating to 2.8.3...

**Comment by tomruijgrok** [comment]
After upgrading to 2.8 it works again. I think this issue can be closed

**Comment by ucheNkadiCode** [comment]
I am still getting this error unfortunately. The problem could be because I am placing the linear gradient insdie of an animated view.

**Comment by ispyco** [comment]
xcode 15.0.1 have same problem in gradient text

**Comment by hoscahmet** [comment]
NOTE
the healthiest, if the project is small, update the react native version

WARNING
Since UIGraphicsBeginImageContext has been deprecated, it may also be caused by other libraries. For example; react-native-fast-image etc. 
also used in older react-native versions

INFO
You can find where they are used by searching UIGraphicsBeginImageContext. Perform the search through xcode.

There is also a short video for the solution: _[https://www.youtube.com/watch?v=psIBtbwMLQE](https://www.youtube.com/watch?v=psIBtbwMLQE)_
